import React from "react";
import Head from "next/head";
import MainPageTemplate from "~/components/MainPageTemplate";
import AboutSection from "~/components/elements/AboutSection";

import img1 from "../../public/images/Banner-about us.jpg";

import Footer from "~/components/elements/footer";
import BannerSection from "~/components/elements/BannerSection";

const About = () => {
  return (
    <div>
      <Head>
        <title>ProIq Academy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPageTemplate>
        <div className="">
          <BannerSection
            paragraphText="About Us"
            imageSrc="/images/Banner-about us.jpg"
            color="#012360"
          />
          <AboutSection />
        </div>
        <Footer />
      </MainPageTemplate>
    </div>
  );
};

export default About;
