import React from "react";
import MainPageTemplate from "~/components/MainPageTemplate";
import FranchisingSection from "~/components/elements/FranchisingSection";
import Footer from "~/components/elements/footer";
import Head from "next/head";

const Franchising = () => {
  return (
    <div>
      <Head>
        <title>ProIq Academy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPageTemplate>
        <div className="sm:pt-[55px] lg:pt-[100px]">
          <FranchisingSection />
        </div>
        <Footer />
      </MainPageTemplate>
    </div>
  );
};

export default Franchising;
