import React from "react";
import MainPageTemplate from "~/components/MainPageTemplate";
import GallerySection from "~/components/elements/GallerySection";

import Footer from "~/components/elements/footer";
import Head from "next/head";
import Image from "next/image";
import img1 from "../../public/images/newpics/img1.jpg";
import img2 from "../../public/images/newpics/img2.jpg";
import img3 from "../../public/images/newpics/img3.jpg";
import img4 from "../../public/images/newpics/img4.jpg";
import img5 from "../../public/images/newpics/img5.jpg";
import img6 from "../../public/images/newpics/img6.jpg";
import img7 from "../../public/images/newpics/img7.jpg";
import img8 from "../../public/images/newpics/img8.jpg";
import img9 from "../../public/images/newpics/img9.jpg";
import img10 from "../../public/images/newpics/img10.jpg";
import img11 from "../../public/images/newpics/img11.jpg";
import img12 from "../../public/images/newpics/img12.jpg";
import img13 from "../../public/images/newpics/img13.jpg";
import img14 from "../../public/images/newpics/img14.jpg";
import img15 from "../../public/images/newpics/img15.jpg";
import img16 from "../../public/images/newpics/img16.jpg";
import img17 from "../../public/images/newpics/img17.jpg";
import img18 from "../../public/images/newpics/img18.jpg";
import img19 from "../../public/images/newpics/img19.jpg";
import img20 from "../../public/images/newpics/img20.jpg";
import img21 from "../../public/images/newpics/img21.jpg";
import img22 from "../../public/images/newpics/img22.jpg";
import img23 from "../../public/images/newpics/img23.jpg";
import img24 from "../../public/images/newpics/img24.jpg";
import img25 from "../../public/images/newpics/img25.jpg";
import img26 from "../../public/images/newpics/img26.jpg";
const Gal: React.FunctionComponent = () => {
  const images = [
    img1,
    img2,
    img3,
    img4,
    img5,
    img6,
    img7,
    img8,
    img9,
    img10,
    img11,
    img12,
    img13,
    img14,
    img15,
    img16,
    img17,
    img18,
    img19,
    img20,
    img21,
    img22,
    img23,
    img24,
    img25,
    img26,
  ];
  return (
    <div>
      <Head>
        <title>ProIq Academy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPageTemplate>
        <div className="relative top-[100px] grid grid-cols-2 gap-4 p-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">
          {images.map((src, index) => (
            <div
              key={index}
              className={`relative overflow-hidden rounded-lg ${
                index % 5 === 0
                  ? "col-span-2 row-span-2"
                  : index % 4 === 0
                  ? "row-span-2"
                  : "h-48"
              }`}
            >
              <Image
                src={src}
                alt={`Gallery image ${index + 1}`}
                fill
                className="object-cover transition-transform duration-300 ease-in-out hover:scale-110"
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 33vw, 20vw"
              />
            </div>
          ))}
        </div>
        <Footer />
      </MainPageTemplate>
    </div>
  );
};
export default Gal;
