import React from "react";
import MainPageTemplate from "~/components/MainPageTemplate";
import GallerySection from "~/components/elements/GallerySection";

import Footer from "~/components/elements/footer";
import Head from "next/head";

const Gallery = () => {
  return (
    <div>
      <Head>
        <title>ProIq Academy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPageTemplate>
        <div className="">
          <GallerySection />
        </div>
        <Footer />
      </MainPageTemplate>
    </div>
  );
};
export default Gallery;
