import Head from "next/head";
import MainPageTemplate from "~/components/MainPageTemplate";
import BackgroundSection from "~/components/elements/BackgroundSection";
import Carousel from "~/components/elements/Carousel";
import ContectSection from "~/components/elements/ContectSection";
import ReviewSection from "~/components/elements/ReviewSection";
import SkillSection from "~/components/elements/SkillSection";
import Strength from "~/components/elements/Strength";
import StudentCommunity from "~/components/elements/StudentCommunity";
import WelcomeSection from "~/components/elements/WelcomeSection";

import Footer from "~/components/elements/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainPageTemplate>
          <Carousel />
          <SkillSection />
          <WelcomeSection />
          <BackgroundSection />
          <Strength />
          <StudentCommunity />
          <ContectSection />
          <ReviewSection />
          <Footer />
        </MainPageTemplate>
      </main>
    </>
  );
}
