import Head from "next/head";
import MainPageTemplate from "~/components/MainPageTemplate";
import Carousel from "~/components/elements/Carousel";
import SkillSection from "~/components/elements/SkillSection";
import Banner from "~/components/elements/Banner";
import Footer from "~/components/elements/footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainPageTemplate>
          <Carousel />
          <SkillSection />
          <Banner />
          <Footer />
        </MainPageTemplate>
      </main>
    </>
  );
}
