import React from "react";
import Head from "next/head";

import MainPageTemplate from "~/components/MainPageTemplate";
import WhyProiqSection from "~/components/elements/WhyProiqSection";

import Footer from "~/components/elements/footer";

const WhyProiq = () => {
  return (
    <div>
      <Head>
        <title>ProIq Academy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPageTemplate>
        <div className="">
          <WhyProiqSection />
        </div>
        <Footer />
      </MainPageTemplate>
    </div>
  );
};

export default WhyProiq;
